// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/catalogs/{catalog}": {
            "post": {
                "description": "Retorna los elementos de un catálogo dado (simulando comportamiento legado).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalogs"
                ],
                "summary": "Obtener Catálogo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nombre del catálogo (ej. Destino, Comunas, SegurosIncendio)",
                        "name": "catalog",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Canal (ej. WEB)",
                        "name": "X-Channel",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comercio (ej. FALABELLA)",
                        "name": "X-Commerce",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID de transacción (ej. 12345)",
                        "name": "X-Transaction-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Entorno a inyectar: dummy, real, o java (por defecto: dummy)",
                        "name": "X-Backend-Env",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handler.catalogItemDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponseDTO"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponseDTO"
                        }
                    },
                    "402": {
                        "description": "Payment Required",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.internalServerErrorDTO"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.catalogItemDTO": {
            "type": "object",
            "properties": {
                "codigo_adm": {
                    "type": "string"
                },
                "descripcion": {
                    "type": "string"
                }
            }
        },
        "handler.errorResponseDTO": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "detail": {
                    "type": "string"
                },
                "errors_detail": {
                    "type": "string"
                },
                "messages": {
                    "type": "array",
                    "items": {}
                }
            }
        },
        "handler.internalServerErrorDTO": {
            "type": "object",
            "properties": {
                "mensaje": {
                    "type": "string"
                },
                "statusCode": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8082",
	BasePath:         "/v1/bfcl/mortgage-loan",
	Schemes:          []string{},
	Title:            "API de Catalogos de Creditos Hipotecarios",
	Description:      "Microservicio en Go para consultar los catalogos legados de creditos hipotecarios.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
